# Generated by Django 6.0.1 on 2026-01-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Khmer-Food', 'Khmer-Food'), ('Burger', 'Burger'), ('Drink', 'Dizza'), ('Pizza', 'Pizza')], max_length=200),
        ),
    ]
