# Generated by Django 6.0.1 on 2026-01-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_checkout_alter_product_category_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Pizza', 'Pizza'), ('Burger', 'Burger'), ('Drink', 'Drink'), ('Khmer-Food', 'Khmer-Food')], max_length=200),
        ),
    ]
