# Generated by Django 6.0.1 on 2026-01-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_product_id_orderitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='decount')),
            ],
        ),
    ]
