# Generated by Django 6.0.1 on 2026-02-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_decount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decount',
            name='image',
            field=models.URLField(max_length=900),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(default=2, max_length=900),
            preserve_default=False,
        ),
    ]
